#! /bin/ksh
#############################################################################
# Licensed Materials # Property of IBM
# 
# Governed under the terms of the International
# License Agreement for Non#Warranted Sample Code.
# 
# (C) COPYRIGHT International Business Machines Corp. 2006
#  All Rights Reserved.
# 
#  US Government Users Restricted Rights # Use, duplication or
#  disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#############################################################################
# SCRIPT: spcat_xml 
# To catalog SQC stored procedures on UNIX
# Catalogs the stored procedures in the simple_xmlproc library 
# simple_xmlproc_drop.db2 uncatalogs the stored procedures if previously cataloged 
# simple_xmlproc_create.db2 catologs the stored procedures 
# Both CLP scripts can be run on their own
# Usage: spcat_xml

db2 -td@ -vf simple_xmlproc_drop.db2
db2 -td@ -vf simple_xmlproc_create.db2

