#t00010.c
#~ CC=C:\Dev-Cpp\bin\gcc.exe -g -Wall
#~ #CCOPTS=-g -Wall
#~ RM=C:\Dev-Cpp\bin\rm.exe
#~ OUTPUTDIR=C:\ccoutput
#~ OBJECTS=t00010.o t00010_1.o
#~ t00010.exe:$(OBJECTS)
	#~ $(CC) -o $(OUTPUTDIR)\t00010.exe $(OBJECTS)
#~ t00010.o:t00010.c
#~ t00010_1.o:t00010_1.c
#~ clean:
	#~ $(RM) *.o


CC=C:\Dev-Cpp\bin\gcc.exe -g -Wall
RM=C:\Dev-Cpp\bin\rm.exe
OUTPUTDIR=C:\ccoutput
#~ OBJECTS=t00085.o t00085p.o
#~ t00085.exe:$(OBJECTS)
	#~ $(CC) -o $(OUTPUTDIR)\t00085.exe $(OBJECTS)
#~ t00085.o:t00085.c
#~ t00085p.o:t00085p.c
#~ clean:
	#~ $(RM) *.o



#单链表-顺序存储结构
OBJECTS=main.o list.o
main.exe:$(OBJECTS)
	$(CC) -o $(OUTPUTDIR)\main.exe $(OBJECTS)
main.o:main.c
list.o:list.c
clean:
	$(RM) *.o


