#! /bin/ksh
#############################################################################
# Licensed Materials # Property of IBM
# 
# Governed under the terms of the International
# License Agreement for Non#Warranted Sample Code.
# 
# (C) COPYRIGHT International Business Machines Corp. 2006
#  All Rights Reserved.
# 
#  US Government Users Restricted Rights # Use, duplication or
#  disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#############################################################################
# SCRIPT: spcat_xquery 
# To catalog XML SQC stored procedures on UNIX
# Catalogs the stored procedures in the xquery_xmlproc library 
# xquery_xmlproc_drop.db2 uncatalogs the stored procedures if previously cataloged 
# xquery_xmlproc_create.db2 catologs the stored procedures 
# Both CLP scripts can be run on their own
# Usage: spcat

db2 -td@ -vf xquery_xmlproc_drop.db2
db2 -td@ -vf xquery_xmlproc_create.db2
