#! /bin/ksh
#############################################################################
# Licensed Materials # Property of IBM
# 
# Governed under the terms of the International
# License Agreement for Non#Warranted Sample Code.
# 
# (C) COPYRIGHT International Business Machines Corp. 1997 - 2002
#  All Rights Reserved.
# 
#  US Government Users Restricted Rights # Use, duplication or
#  disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#############################################################################
# SCRIPT: spcat 
# To catalog SQLj stored procedures on UNIX
# Catalogs the stored procedures in the SpServer library 
# SpDrop.db2 uncatalogs the stored procedures if previously cataloged 
# SpCreate.db2 catologs the stored procedures 
# Both CLP scripts can be run on their own
# Usage: spcat

db2 -td@ -vf SpDrop.db2
db2 -td@ -vf SpCreate.db2
