#! /bin/ksh
#############################################################################
# Licensed Materials # Property of IBM
# 
# Governed under the terms of the International
# License Agreement for Non#Warranted Sample Code.
# 
# (C) COPYRIGHT International Business Machines Corp. 1997 - 2002
#  All Rights Reserved.
# 
#  US Government Users Restricted Rights # Use, duplication or
#  disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#############################################################################
# SCRIPT: udfcat 
# To catalog SQLj user-defined functions on UNIX
# Catalogs the user-defined functions in the UDFsrv library 
# UDFDrop.db2 uncatalogs the functions if previously cataloged 
# UDFCreate.db2 catalogs the user-defined functions 
# Both CLP scripts can be run on their own
# Usage: udfcat

db2 -td@ -vf UDFDrop.db2
db2 -td@ -vf UDFCreate.db2
