#t00010.c
CC=C:\Dev-Cpp\bin\gcc.exe
RM=C:\Dev-Cpp\bin\rm.exe
OUTPUTDIR=C:\ccoutput
OBJECTS=t00010.o t00010_1.o
t00010.exe:$(OBJECTS)
	$(CC) -o $(OUTPUTDIR)\t00010.exe $(OBJECTS)
t00010.o:t00010.c
t00010_1.o:t00010_1.c
clean:
	$(RM) *.o

