#t00010.c
#~ CC=C:\Dev-Cpp\bin\gcc.exe -g -Wall
#~ #CCOPTS=-g -Wall
#~ RM=C:\Dev-Cpp\bin\rm.exe
#~ OUTPUTDIR=C:\ccoutput
#~ OBJECTS=t00010.o t00010_1.o
#~ t00010.exe:$(OBJECTS)
	#~ $(CC) -o $(OUTPUTDIR)\t00010.exe $(OBJECTS)
#~ t00010.o:t00010.c
#~ t00010_1.o:t00010_1.c
#~ clean:
	#~ $(RM) *.o


CC=C:\Dev-Cpp\bin\gcc.exe -g -Wall
RM=C:\Dev-Cpp\bin\rm.exe
OUTPUTDIR=C:\ccoutput
#~ OBJECTS=t00085.o t00085p.o
#~ t00085.exe:$(OBJECTS)
	#~ $(CC) -o $(OUTPUTDIR)\t00085.exe $(OBJECTS)
#~ t00085.o:t00085.c
#~ t00085p.o:t00085p.c
#~ clean:
	#~ $(RM) *.o




OBJECTS=t00090m.o t00090e.o
t00090m.exe:$(OBJECTS)
	$(CC) -o $(OUTPUTDIR)\t00090m.exe $(OBJECTS)
t00090m.o:t00090m.c
t00090e.o:t00090e.c
clean:
	$(RM) *.o


